import os
import tkinter as tk
import sys
import time
import json
import subprocess
print("[+] ----------------RED WHİTE SHADOW----------------------[+]")
print("[-] Author : RED WHİTE SHADOW ")
print("[-] GİT HUB : https://github.com/red-white-shadow ")
print("[-] İNSTAGRAM : https://instagram.com/toxic_red_white_shad0w ")
print("[+] ----------------RED WHİTE SHADOW----------------------[+]")
print("[+] ----------------RED WHİTE SHADOW----------------------[+]")
target= input("[+]Target -> : ")
data = subprocess.check_output(["curl",f"http://ip-api.com/json/" + target ]).decode("utf-8")
json.loads(data)
i=tk.Tk()
i.configure(background='black')
i.geometry("900x550")
i.title("İp Tracer : Red White Shadow")
greeta = tk.Label(i,text="coder : Red White Shadow",font='Verdana 15', bg="black" , fg="white")
greeta.grid(column=0, row=1)
greet = tk.Label(i,text=json.loads(data)["city"],font='Verdana 15', bg="black" , fg="white")
greet.grid(column=1, row=1)
greet1 = tk.Label(i,text=json.loads(data)["country"],font='verdana 15', bg="black" , fg="white")
greet1.grid(column=1, row=2)
greet2 = tk.Label(i,text=json.loads(data)["region"],font='verdana 15', bg="black" , fg="white")
greet2.grid(column=1, row=3)
greet3 = tk.Label(i,text=json.loads(data)["countryCode"],font='verdana 15', bg="black" , fg="white")
greet3.grid(column=1, row=4)
greet4 = tk.Label(i,text=json.loads(data)["zip"],font='verdana 15', bg="black" , fg="white")
greet4.grid(column=1, row=5)
greet5 = tk.Label(i,text=json.loads(data)["zip"],font='verdana 15', bg="black" , fg="white")
greet5.grid(column=1, row=6)
greet6 = tk.Label(i,text=json.loads(data)["lat"],font='verdana 15', bg="black" , fg="white")
greet6.grid(column=1, row=7)
greet7 = tk.Label(i,text=json.loads(data)["lon"],font='verdana 15', bg="black" , fg="white")
greet7.grid(column=1, row=8)
greet8 = tk.Label(i,text=json.loads(data)["timezone"],font='verdana 15', bg="black" , fg="white")
greet8.grid(column=1, row=9)
greet9 = tk.Label(i,text=json.loads(data)["isp"],font='verdana 15', bg="black" , fg="white")
greet9.grid(column=1, row=10)
greet10 = tk.Label(i,text=json.loads(data)["org"],font='verdana 15', bg="black" , fg="white")
greet10.grid(column=1, row=11)
greet11 = tk.Label(i,text=json.loads(data)["as"],font='verdana 15', bg="black" , fg="white")
greet11.grid(column=1, row=12)
greet12 = tk.Label(i,text=json.loads(data)["query"],font='verdana 15', bg="black" , fg="white")
greet12.grid(column=1, row=13)
i.mainloop()
